export { default as Hero }      from './Hero'
export { default as Servicios } from './Servicios'
export { default as Clientes }  from './Clientes'
export { default as Arte }      from './Arte'
export { default as Contactos } from './Contactos'
